import * as React from 'react';
import ThemeRegistry from "@/components/ThemeRegistry";
import Box from "@mui/material/Box";
import ColorSchemeToggle from "@/components/ColorSchemeToggle";

export const metadata = {
  title: 'OctoPluginStats',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
    <body>
    <ThemeRegistry>
      <ColorSchemeToggle />
      <Box sx={{
        height: "100vh",
        overflowY: "scroll",
        scrollSnapType: "y mandatory",
        "& > div": {
          scrollSnapAlign: "start"
        }
      }}>
        {children}
      </Box>
    </ThemeRegistry>
    </body>
    </html>
  );
}